version: '3'

services:
  db:
    image: postgres:13.6
    ports:
      - 5432:5432
    volumes:
      - /postgres_data:/var/lib/postgresql/data/
      - ./database/film_work_data.sql:/docker-entrypoint-initdb.d/film_work_data.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    volumes:
      - static_value:/code/app/static_files/
      - media_value:/code/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.compression=true
      - http.max_content_length=500mb
    depends_on:
      - db
#  etl01:
#    build: ../01_etl/
#    env_file:
#      - ../01_etl/.env
volumes:
  postgres_data:
  static_value:
  media_value:
